import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { useState } from 'react';
import './globals.css'
import Link from 'next/link';
import SideNav from './ui/sidenav';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`flex flex-row ${inter.className}`}>
        <header className="basis-20 max-w-20 h-screen">
          <SideNav />
        </header>
        {children}
      </body>
    </html>
  )
}
